henrygd/beszel

readme.md

Hi, if you do not mind I added some instructions on how to run binaries in the background as system service. With this added it is more linux-newbie friendly.
Feel free to let me know if you think this is too much.
I can also add OIDC instruction for Authentik if you want me but that is mainly for PocketBase. Feel free to let me know.

Add instruction to run hub and agent as system service

---

readme.md
supplemental/scripts/install-agent.sh
supplemental/scripts/install-hub.sh

As discussed in issue #41, I've created installation scripts for Beszel Agent and Hub to simplify the deployment process. This pull request builds on top of the changes introduced in #77 .
The installation scripts are designed to work on Debian and Ubuntu distributions, and they handle the installation and configuration of the Beszel Agent and Hub services.
Please review the changes and let me know if you have any feedback or suggestions. I'm open to making adjustments and improvements! 😊

Add Install scripts for agent/hub + documentation in the readme

---

beszel/internal/agent/agent.go
beszel/internal/entities/system/system.go
beszel/site/src/components/systems-table/systems-table.tsx
beszel/site/src/types.d.ts

Resubmit of #109 to fulfill #105 
The only somewhat messy thing that I had to do following the refactor was to add an import for the main _module_ (not sure if that is the right terminology when using Go) in the `internal/agent/agent.go` as the version information was moved outside of the agent module itself.
Additionally, it adds an import for the _Wifi_ icon to be used on the hub table.

Adds a version listing in the hub for each agent

---

beszel/internal/agent/agent.go

Resubmit for #111
Once again, I'm not 100% sure the addition of the check for the "starting" string will necessarily fix #103, but it shouldn't hurt. The only downside is that containers which do not have a properly configured health check will not load data.

Fixes edge cases where container health message does not have expected suffix

---

beszel/site/src/index.css

I simply changed the default scrollbar to have transparent background and use the border color to match beszel's theme. Here is a preview with 175% zoom:
And in light mode:

feat: style scrollbar

---

readme.md

Hi @henrygd - here some minor changes to enhance the `README.md`. Keep the good work up!
- Changed some wording to make it a bit clearer
- CamelCase headings
- Added License reference

Enhanced README.md

---

beszel/internal/alerts/alerts.go

characters like space would be escaped to `+` instead of `%20`, this makes the url in alert message invalid if system name contains space

fix: path escape for system name in alert message

---

beszel/internal/hub/hub.go

https://github.com/henrygd/beszel/blob/4e64d9efad9299c29f96c8a892adbad89c726ab8/beszel/internal/hub/hub.go#L374
The primary issue with the code is its inability to handle IPv6 addresses. The hostname we provides may include hostname or both IPv4 and IPv6 addresses. However, the `ssh.Dial` function expects an address in the format host:port, which might not be directly compatible with IPv6 addresses, especially when they contain multiple colons. So i use `net.JoinHostPort` to fix ipv6 address at createSystemConnection.
After fix, it can handle ipv6 address currectly now. I tested with dualstack domain, single ipv4/ipv6 domain and single ipv4/ipv6 address, it all works fine now.
The only change for IPv6 address now is not require a `[]`, just input the ip.

fix IPv6 connection problem

---

supplemental/scripts/install-agent.sh

Users in mainland China frequently encounter issues when installing beszel-agent:
- GitHub access is blocked or extremely slow
- Downloads frequently timeout and fail
- MitM Risks Frequent in the internet
This commit adds support for GitHub mirrors to resolve network issues:
- New `--china-mirrors` flag to use ghp.ci mirror for reliable downloads
- Implement checksum verification for downloaded files
- Add progress bar for file downloads
- Better error messages for troubleshooting
```sh
./install-agent.sh --china-mirrors ...
```
The ghp.ci mirror is widely used in China and provides reliable access to GitHub resources. This solution follows similar patterns used by other popular open-source projects to support users in mainland China.
---
Thank you for taking the time to review this PR! …

Fix GitHub.com access issues in mainland China & Add checksum support

---

supplemental/scripts/install-agent.sh
supplemental/scripts/install-hub.sh

Some linux distro(like suse) would complain if user set `Restart=always`, but have not included any `StartLimitIntervalSec`, `StartLimitBurst`, or `RestartSec` directives to prevent the service from entering an infinite Start request repeated too quickly loop
```
luna:~ # systemctl status beszel-hub
× beszel-hub.service - Beszel Hub Service
Loaded: loaded (/etc/systemd/system/beszel-hub.service; enabled; preset: disabled)
Active: failed (Result: start-limit-hit) since Tue 2024-12-03 21:35:01 CST; 2s ago
Duration: 42ms
Process: 13519 ExecStart=/opt/beszel/beszel serve --http 0.0.0.0:10002 (code=exited, status=0/SUCCESS)
Main PID: 13519 (code=exited, status=0/SUCCESS)
CPU: 18ms
Dec 03 21:35:01 luna systemd[1]: beszel-hub.service: Scheduled restart job, restart counter is at 5.
Dec 03 …
```

chore: add restartsec to systemd service file

---

beszel/site/src/components/systems-table/systems-table.tsx

- Add toggle button to switch between table and grid layouts
- Implement card-based grid view with system metrics
- Add sort dropdown menu for grid view
- Display system status, metrics with icons and labels
- Improve handling of long system names
- Maintain consistent sorting and filtering between views
- Persist view preference in localStorage

feat: add grid view option for systems table

---

beszel/internal/records/records.go

`json.Unmarshal` was reusing the same `Stats` struct, leading to incorrect values when unmarshaling multiple JSON strings. This commit creates a new `Stats` instance in each loop iteration to resolve the issue.
A reproducible example is available on Go Playground: https://go.dev/play/p/HnZ8-z7hgXq

fix: json.Unmarshal not resetting struct fields

---

beszel/internal/hub/hub.go

This pull request makes a small improvement to the `startSystemUpdateTicker` function by using `time.Tick` instead of `time.NewTicker`. This change aligns with Go 1.23's recommendation and can lead to slightly cleaner code.
According to the Go 1.23 documentation, the garbage collector can now recover unreferenced tickers created with `time.Tick`, making `time.NewTicker` method unnecessary in most cases.
Reference:
* time.Tick: https://pkg.go.dev/time#Tick

refactor: simplify `startSystemUpdateTicker` using `time.Tick`

---

beszel/go.mod
beszel/go.sum

This PR upgrades the `gopsutil` dependency to address a memory leak issue specifically on ARM Mac systems. The upstream fix has been merged in shirou/gopsutil#1767 and shirou/gopsutil#1768.

Upgrade gopsutil to fix memory leak on ARM Mac

---

beszel/cmd/agent/agent.go

This PR adds support for reading the agent SSH key from a file. This allows storing the agent key as a docker secret. 
I'm not a Go dev so let me know if there's a better way to do this but it's pretty straightforward

adding reading agent ssh key from file

---

beszel/site/src/components/login/auth-form.tsx

In some languages (e.g., German), nouns begin with a capital letter. This PR removes the forced lowercasing of password placeholders on the login page to display the text exactly as translated in the language files.
Before:
After:

remove forced lowercasing of password placeholders in login page

---

supplemental/scripts/install-agent.sh

Modified the install-agent.sh script for binary installation to support OpenWRT.
I more or less tried to match your coding style, checking the OS type like you did with Alpine. 
To add the service, instead of systemd a procd init script is used. The service can be enabled, started, stoped, etc. by using 
`service beszel-agent ...`. 
An update command is also included to update and restart the service. For automatic updates, I opted to use a crontab job that uses `service beszel-agent update` once a day. 
To get the OS type variable, `sed`  is used instead of  `tr`, since most busybox systems have implmentations of `tr`  that do not support classes, as mentioned in [this issue](https://github.com/dehydrated-io/dehydrated/issues/285). This implementation is not the pretiest, since all 27 …

Add OpenWRT support for binary quick script installation

---

.github/ISSUE_TEMPLATE/BUG_REPORT_FORM.yml
.github/ISSUE_TEMPLATE/FEATURE_REQUEST_FORM.yml
.github/ISSUE_TEMPLATE/config.yml

As this project gets more and more popular there will be more Feature Requests and bug reports. As there is currently no structure for these. This PR add templates for both of them. Which hopefully makes your life a bit easier 😄 
- Add checkbox that the docs has been checked
- Add checkbos that open and closed issues has been searched for similar  problems. 
- Add `description` field
- Add `Expected Behavior` field
- Add `Steps to Reproduce` field
- Add multiple fields to collection information about the installation
- Add checkbos that open and closed requests has been searched for similar requests.
- Add dropdown to select the section (Charts, Notifications, metrics collection etc)
- Add description field 
Let me know if you want any changes to this, happy to adjust it to your wishes 😄

[QoL] Add Bug and Feature Request template

---

supplemental/scripts/install-agent.sh
supplemental/scripts/install-hub.sh

`https://ghp.ci/` is outdated and current working version is `https://ghfast.top/`
Consider this address could change often and there are many available, better make it configurable. 
Also made the install-hub.sh compatible with china-mirrors

Enhance proxy handling in install scripts for GitHub mirrors

---

beszel/.goreleaser.yml

This change adds a riscv build config to for the agent to goreleaser. As far as I am aware, only freebsd and linux supports this, so ignore mac and windows.
Verified to work on a [VisionFive 2 SBC](https://www.starfivetech.com/en/site/boards).
I have not updated any installation scripts as that looks like witchcraft to me.

feat(release): add riscv agent builds to goreleaser config

---

beszel/.goreleaser.yml
supplemental/debian/beszel-agent.service
supplemental/debian/config.sh
supplemental/debian/copyright
supplemental/debian/lintian-overrides
supplemental/debian/postinstall.sh
supplemental/debian/postrm.sh
supplemental/debian/prerm.sh
supplemental/debian/templates

Adds a Debian package to the build. Currently, only `beszel-agent` is packaged, but a package for `beszel-hub` could be added too. Since the SSH key is a required configuration option, the package prompts for it during installation.
This is the first step. The next step would be to set up a Debian repo for the packages.
Run the build:
```bash
goreleaser release --snapshot --clean
```
This produces four `.deb` files in the `dist` directory, for amd64, arm64, armv6, riscv64, and mips64_hardfloat (architectures were already configured in the goreleaser config)
Create a new Debian VM
Install package:
```bash
cd /tmp
wget https://d.ls/debian/beszel-agent_0.9.1-SNAPSHOT-1747b00_linux_amd64.deb
sudo apt install ./beszel-agent_0.9.1-SNAPSHOT-1747b00_linux_amd64.deb
```
Output:
``` …
```

Create Debian package for beszel-agent

---

beszel/site/src/components/add-system.tsx

Adding `version: "3"` makes this compatible with more recent docker tools.
Otherwise get error:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'beszel-agent'
```

Update add-system.tsx docker-compose.yml template.

---

beszel/cmd/agent/agent.go

I'm running the beszel-agent on Windows as a permanently running scheduled task in system context to avoid needing alternative programs like NSSM for running it in the background. As the Windows task scheduler provides support for supplying startup arguments I prefer to directly supply key and port via the commandline to be able to manage everything at one place.  
Changes:
* Added support for `-key` and `-port` flags to allow users to specify the public key and port number directly from the command line.
* Updated the usage information to provide a clear guide on available options and subcommands.
* Modified the logic to prioritize the `-key` flag over the `KEY` environment variable and the `-port` flag over the `PORT` environment variable.
* Enhanced error messaging to include …

add beszel-agent startup arguments

---

.github/workflows/docker-images.yml

This pull request proposes a change to publish the Docker images to the GitHub Container Registry (ghcr.io).  
According to the [Docker Hub documentation](https://docs.docker.com/docker-hub/usage/), unauthenticated pulls will be restricted to 10 pulls/h starting April 1, 2025. This limitation may be insufficient in environments with scheduled auto-update mechanisms for multiple containers.
The GitHub Container Registry is free for public repositories and does not appear to have an officially documented rate limit at this time.

Publish Docker images to GitHub container registry

---

supplemental/scripts/install-agent.sh

Hi, first off, thanks for such a great project!
This pull request adds a new option to the installer script that allows users to automatically enable daily updates without being prompted for confirmation. By simply passing the --auto-update parameter when running the script, the auto-update feature will be enabled, streamlining the installation process for automated deployments or non-interactive environments.
Key Changes:
- New Flag: Introduced a new flag (--auto-update) in the argument parser.
- Conditional Checks: Modified the sections for Alpine, OpenWRT, and systemd setups to check for the new flag and automatically set the auto-update option.
- Non-interactive Mode: When the flag is used, the script bypasses the prompt and directly sets up the daily update service.
Sample Output: …

Add --auto-update Option to Agent Installer Script

---

beszel/.goreleaser.yml

This enables agent binaries for OpenBSD.
Tested it on a couple of machines -- no issues.

Agent OpenBSD release

---

beszel/internal/agent/docker.go
beszel/internal/entities/container/container.go

The Docker daemon's API returns different values on Windows and non-Windows systems. This impacts the calculation of the `cpuPct` and `usedMemory` statistics. The systems are disciminate on the `Server` header send by the server. Uses the unix stats calculation in case the header is not set.
`docker stats` implementation for reference:
https://github.com/docker/cli/blob/master/cli/command/container/stats_helpers.go#L100

compute cpu and memory stats for windows docker daemon

---

supplemental/debian/postinstall.sh

Enable docker in the Debian package to match the main install script
Upgrade
```
dpkg: warning: downgrading beszel-agent (0.11.1) to (0.0.0~SNAPSHOT-b05966d)
(Reading database ... 118364 files and directories currently installed.)
Preparing to unpack beszel-agent_0.0.0-SNAPSHOT-b05966d_linux_amd64.deb ...
Unpacking beszel-agent (0.0.0~SNAPSHOT-b05966d) over (0.11.1) ...
Setting up beszel-agent (0.0.0~SNAPSHOT-b05966d) ...
Adding beszel to docker group
```
```
$ grep docker /etc/group
docker:x:987:beszel
```
On fresh install without docker, doesn't add
```
Unpacking beszel-agent (0.0.0~SNAPSHOT-b05966d) ...
Setting up beszel-agent (0.0.0~SNAPSHOT-b05966d) ...
Creating beszel group
Creating beszel user
Created symlink '/etc/systemd/system/multi-user.target.wants/beszel-agent.service' → …
```

Add docker support in Debian package

---

supplemental/scripts/install-agent.ps1

- This PR fixes an issue related to #915.
- Suppressed the output of “scoop install beszel-agent” so that the service path contains only the executable location, preventing NSSM from storing the install message.
- ❌ Problem occurred on: **Windows Server 2019 Standard**
- ✅ Issue resolved and verified on: **Windows Server 2019 Standard**

fix(install): suppress scoop output to avoid nssm path pollution (related to #915)

---

.github/workflows/label-from-dropdown.yml

This PR fixes the labels not being applied for all dropdowns. I forgot to adjust that part after the suggested changes in the orginal PR. Sorry for that. 
- CI Job was not looking at `Metrics `and `Categories` to apply those labels.

[Chore] Fix CI lables

---

beszel/Makefile
beszel/internal/agent/system.go
beszel/internal/alerts/alerts.go
beszel/internal/alerts/alerts_system.go
beszel/internal/entities/system/system.go
beszel/migrations/1_collections_snapshot_0_12_0.go
beszel/site/src/components/alerts/alert-button.tsx
beszel/site/src/components/charts/load-average-chart.tsx
beszel/site/src/components/routes/system.tsx
beszel/site/src/components/systems-table/systems-table.tsx
beszel/site/src/components/ui/collapsible.tsx
beszel/site/src/lib/utils.ts
beszel/site/src/types.d.ts

This PR enhances the recently added Load Averages feature by improving visibility, usability, and alert consolidation.
- Added the 1-minute load average alongside the existing 5- and 15-minute values.
- We use the core count to calculate the bar.
- Consolidated all three load averages into a single column, with a hover tooltip to reveal the 1m, 5m, and 15m figures.
- Introduced a chart to track load average trends over time, giving users deeper insight into system performance.
- Included the 1-minute load average in alert notifications for quicker spike detection.
- Grouped all Load Average alerts into a single collapsible section to reduce dashboard clutter.
Please review and let me know if any tweaks are needed!

[Feature][0.12.0-Beta] Enhance Load Average Display, Charting & Alert Grouping

---

beszel/Makefile
beszel/internal/alerts/alerts_history.go
beszel/internal/alerts/alerts_system.go
beszel/internal/hub/hub.go
beszel/internal/users/users.go
beszel/migrations/1_create_alerts_history.go
beszel/site/package-lock.json
beszel/site/package.json
beszel/site/src/components/alerts-history-columns.tsx
beszel/site/src/components/routes/settings/alerts-history-data-table.tsx
beszel/site/src/components/routes/settings/general.tsx
beszel/site/src/components/routes/settings/layout.tsx
beszel/site/src/lib/stores.ts
beszel/site/src/types.d.ts

This PR introduces a new page to track the history of all alert results. For now, the page is located under the **Settings** section, as I could not find a better place for now.
- `alert_history` collection to store alert result history  
- `alert_history` module to manage related logic  
- UI page with a table to **view**, **export**, and **delete** alert history

[Feature] Add Alerts History page

---

beszel/site/src/components/systems-table/systems-table.tsx

This PR moves the "Copy name button" to the Action Dialog not prevent from copying the name when trying to opening the system
Closes https://github.com/henrygd/beszel/issues/1007
- Move Copy name to Action Dialog

[Feature] Move name copy to Action Dialog

---

beszel/internal/agent/update.go
beszel/internal/hub/update.go
supplemental/scripts/install-agent.sh

This PR (hopefully) improves the auto update mechanism.
closes https://github.com/henrygd/beszel/issues/1006
closes https://github.com/henrygd/beszel/issues/469
- Add the service restart to the `update.go` for the agent and hub
- Use the build-in update command to update the agent and hub on the timer
- creation of the `run-update.sh`

[Chore] Improve auto update mechanism 

---

beszel/dockerfile_agent_nvidia

This changes the docker cuda image from `12.9.1` to `12.2.2` for increased compatibility.
For example, if you install [the `nvidia-driver` package from the debian trixie repos](https://packages.debian.org/en/trixie/nvidia-driver) from their repo [as recommended](https://wiki.debian.org/NvidiaGraphicsDrivers) you get cuda `12.4` and this error.
```
nvidia-container-cli: requirement error: unsatisfied condition: cuda>=12.9, please update your driver to a newer version, or use an earlier cuda container: unknown
```
I'm implementing the second suggestion here. [`cuda:12.2.2-base-ubuntu22.04` is supported](https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/supported-tags.md#cuda-1222) and as far as I know (please correct me if I'm wrong) this has no disadvantages for this project. …

Use older cuda image for increased compatibility

---

beszel/.goreleaser.yml

Goreleaser performs truthy evaluation on templates. As `.Env.IS_FORK` is a string, the env variable containing a non empty-string already evaluated to true which causes the external asset releases to always be skipped.
resolves #1144
- fixed official release workflow for winget, scoop, homebrew
- external releases of winget, scoop, homebrew for the official repository
- test in my fork without any code modification:  
https://github.com/a-mnich/beszel/actions/runs/17503917759/job/49723165161
- test in my fork with `IS_FORK: ${{ github.repository_owner != 'a-mnich' }}` - (simulation of a release in the offical repository):   https://github.com/a-mnich/beszel/actions/runs/17503935051/job/49723218947
An error is expected here as I don't have access to the winget and brew repositories.

[FIX] fix brew, winget, scoop release workflow

---

supplemental/scripts/install-agent.sh

Adding openwrt restart procedure after updating the agent automatically
Add a link to the PR for [documentation](https://github.com/henrygd/beszel-docs) changes.
restart section
```
restart_service() {
stop
start
}
```
Command that runs after agent update
Replaced:
`       start_service`
with:
`        /etc/init.d/beszel-agent restart`

Adding openwrt restart procedure after updating the agent automatically

---

agent/update.go

Fixes for:
```
No supported init system detected; please restart manually if needed.
```
- Direct `procd` detection for OpenWrt
- Correct order of command which is `service beszel-agent restart`

Fixed OpenWRT agent restarter logic

---

internal/dockerfile_agent
internal/dockerfile_agent_intel
internal/dockerfile_agent_nvidia
internal/dockerfile_hub

This PR addresses issue #1214 by adding built-in data persistence to Beszel's agent containers.
Many users deploy Beszel with automated container update tools like Watchtower. If they forget (or don't know) to mount a volume for `/beszel_data`, all configuration is lost every time the container is automatically replaced — leading to unexpected resets and a poor user experience.
To prevent this, i add the following line to all agent Dockerfiles:
```dockerfile
VOLUME ["/beszel_data"]

Fix #1214: Add VOLUME ["/beszel_data"] to preserve config across container recreations

---

supplemental/scripts/install-agent.sh

- This message:
```
Restarting beszel-agent via procd…
Terminated
```
When you use USE_PROCD=1, procd automatically tracks and stops the process it started.
So normally, you don’t need to manually kill the process — procd does that cleanly on stop_service().
If you override stop_service() with killall, you’re:
Bypassing procd’s PID tracking
Potentially killing unrelated instances
Losing logging and restart behavior consistency
- Added respawn if crashes (default 5s, 5 attempts in 5min)

OpenWRT - graceful service stop, restart and respawn if crashes
